// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Geofence struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Area      interface{} `json:"area"`
	CreatedAt time.Time   `json:"created_at"`
}

type GeofenceEvent struct {
	ID         uuid.UUID `json:"id"`
	GeofenceID uuid.UUID `json:"geofence_id"`
	DeviceID   string    `json:"device_id"`
	EventType  string    `json:"event_type"`
	Timestamp  time.Time `json:"timestamp"`
}

type Location struct {
	ID        uuid.UUID       `json:"id"`
	DeviceID  string          `json:"device_id"`
	Latitude  float64         `json:"latitude"`
	Longitude float64         `json:"longitude"`
	Geom      interface{}     `json:"geom"`
	H3Ix      interface{}     `json:"h3_ix"`
	Accuracy  sql.NullFloat64 `json:"accuracy"`
	Heading   sql.NullFloat64 `json:"heading"`
	Speed     sql.NullFloat64 `json:"speed"`
	IsMock    sql.NullBool    `json:"is_mock"`
	CreatedAt sql.NullTime    `json:"created_at"`
}
