// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateGeofence(ctx context.Context, arg CreateGeofenceParams) (CreateGeofenceRow, error)
	// Guarda una nueva ubicación y devuelve el ID insertado.
	CreateLocation(ctx context.Context, arg CreateLocationParams) (uuid.UUID, error)
	DeleteGeofence(ctx context.Context, id uuid.UUID) error
	FindGeofencesContainingPoint(ctx context.Context, arg FindGeofencesContainingPointParams) ([]FindGeofencesContainingPointRow, error)
	GetDriverRoute(ctx context.Context, deviceID string) (string, error)
	GetGeofences(ctx context.Context) ([]GetGeofencesRow, error)
	// Obtiene la última ubicación conocida de un dispositivo.
	GetLatestLocationByDevice(ctx context.Context, deviceID string) (Location, error)
	// Busca conductores dentro de un radio (en metros) usando PostGIS.
	// ST_DWithin usa índices espaciales, así que es ULTRA rápido.
	GetNearbyDrivers(ctx context.Context, arg GetNearbyDriversParams) ([]GetNearbyDriversRow, error)
	LogGeofenceEvent(ctx context.Context, arg LogGeofenceEventParams) error
	UpdateGeofence(ctx context.Context, arg UpdateGeofenceParams) (UpdateGeofenceRow, error)
}

var _ Querier = (*Queries)(nil)
